/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "chat-history": () => import("@/views/chat-history/index.vue"),
  chat: () => import("@/views/chat/index.vue"),
  "invite-code": () => import("@/views/invite-code/index.vue"),
  "knowledge-base": () => import("@/views/knowledge-base/index.vue"),
  "model-provider": () => import("@/views/model-provider/index.vue"),
  "org-tag": () => import("@/views/org-tag/index.vue"),
  "personal-center": () => import("@/views/personal-center/index.vue"),
  "recharge-manage": () => import("@/views/recharge-manage/index.vue"),
  recharge: () => import("@/views/recharge/index.vue"),
  "usage-monitor": () => import("@/views/usage-monitor/index.vue"),
  user: () => import("@/views/user/index.vue"),
};
